server:
  port: ${LOCAL_SERVER_PORT}

spring:
  config:
    activate:
      on-profile: local
    include: env

  datasource:
    master:
      hikari:
        username: ${LOCAL_DB_MASTER_USERNAME}
        password: ${LOCAL_DB_MASTER_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://${LOCAL_DB_MASTER_IP}:${LOCAL_DB_MASTER_PORT}/${LOCAL_DB_MASTER_SCHEMA}?useUnicode=yes&characterEncoding=UTF-8
        pool-name: ${LOCAL_DB_MASTER_POOL}

    slave:
      hikari:
        username: ${LOCAL_DB_SLAVE_USERNAME}
        password: ${LOCAL_DB_SLAVE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://${LOCAL_DB_SLAVE_IP}:${LOCAL_DB_SLAVE_PORT}/${LOCAL_DB_SLAVE_SCHEMA}?useUnicode=yes&characterEncoding=UTF-8
        pool-name: ${LOCAL_DB_SLAVE_POOL}


springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.news_agent


logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul                                          # Appender pattern for log date format. (Only supported with the default Logback setup.)
    console: "%magenta(%d{yyyy-MM-dd HH:mm:ss.SSS}) %highlight(%-3level) %cyan(- %class{0}.java:%line) %msg %n"
    file: "[%d{MM-dd HH:mm:ss.SSS}][%-5level][%logger.%method:%line] - %msg%n"              # The log pattern to use in a file (if LOG_FILE is enabled). (Only supported with the default Logback setup.)
    rolling-file-name: "./logs/news_agent/news_agent.%d{yyyy-MM-dd}.%i.log"
  file: # If defined, it is used in the default log configuration.
    name: "./logs/news_agent.log"
    max-history: 30                                                                         # Maximum number of archive log files to keep (if LOG_FILE enabled). (Only supported with the default Logback setup.)
    max-size: 100MB                                                                         # Maximum log file size (if LOG_FILE enabled). (Only supported with the default Logback setup.)

  level:
    root: info
    com:
      mm:
        sett: debug
      zaxxer:
        hikari:
          HikariConfig: DEBUG
          pool: off
    com.mm.sett.api.mapper: off
    org:
      springframework:
        web:
          client: debug   # display log for SNS interface
    jdbc:
      sqlonly: off
      sqltiming: debug
      audit: off
      resultset: off
      resultsettable: debug
      connection: off
    log4jdbc:
      log4j2: info


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


##### util config #####
util-config:
  scheduling:
    # scheduling period
    1_hours: # per 1 hours
      batch_scheduled_news_cron_job: "3600000"

    3_hours: # per 3 hours
      batch_scheduled_news_cron_job: "10800000"

    6_hours: # per 6 hours
      batch_scheduled_news_cron_job: "21600000"

    9_hours: # per 9 hours
      batch_scheduled_news_cron_job: "32400000"

    12_hours: # per 12 hours
      batch_scheduled_news_cron_job: "43200000"

    15_hours: # per 15 hours
      batch_scheduled_news_cron_job: "54000000"

    18_hours: # per 18 hours
      batch_scheduled_news_cron_job: "64800000"

    21_hours: # per 21 hours
      batch_scheduled_news_cron_job: "75600000"

    24_hours: # per 24 hours
      batch_scheduled_news_cron_job: "86400000"

  # old new data clean period (per 1 year)
  batch_config:
    old_news_clean_period: 31557600

  # News API config
  news_api:
    api_url: ${LOCAL_NEWS_API_URL}
    api_key: ${LOCAL_NEWS_API_KEY}
    api_host: ${LOCAL_NEWS_API_HOST}

  # HTTP config
  http_config:
    connect_time_out: 300 # 5분
    read_time_out: 300 # 5분
    write_time_out: 300 # 5분